=begin
#REST API documentation

#<p>Base Path: https://api.tempo.io/4</p> <div style=\"background-color: #E5F9FD;padding: 15px;margin: 20px 0;\">   This documentation is for <strong>version 4</strong> of the Tempo REST API, which is the latest version. To read documentation for version 3 of the Tempo REST API, <a href=\"https://apidocs.tempo.io/v3\"><strong>click here</strong></a>  </div>  We encourage you to join our developer community on Slack at [www.tempo.io/developers](https://www.tempo.io/developers), where you can get support from our internal experts and share best practices with other developers building with Tempo.  If you have feedback or requests, you can also reach us through our Customer Support Portal. You can find general product  information in the Tempo Help Center.  Below are links to other Tempo APIs. <ul>   <li><a href=\"https://apidocs.tempo.io/audit\">Audit API</a></li>   <li><a href=\"https://apidocs.tempo.io/cost-tracker\">Cost-Tracker API</a></li>   <li><a href=\"https://apidocs.tempo.io/jira\">Jira Links API</a></li> </ul>  ## Authentication ### Using the REST API as an individual user  You can use the REST API to interact with the data your permissions give you access to. To do so, you will need to  generate a Tempo OAuth 2.0 token.  Go to **Tempo>Settings**, scroll down to **Data Access** and select **API integration**.  Once you have a token, you need to use it inside the Authorization HTTP header. Ex:  `curl -v -H \"Authorization: Bearer $token\" \"https://api.tempo.io/4/worklogs?...\"`<br><br>  ### Using the REST API as an application developer  If you are building apps with Tempo, and have the required Tempo administrator permissions, you can quickly  obtain the OAuth 2.0 credentials you need to retrieve an access token. Access tokens grant temporary, secure  access to Tempo, based on your current permissions.  #### Obtain your credentials  Go to **Tempo>Settings**, scroll down to **Data Access** and select **OAuth 2.0 authentication**.  Enter a Redirect URI and specify the Client type and Authorization grant type. In most cases you will choose Authorization code as the Authorization grant type.  Once you click **Add**, your Client ID and Client secret are generated and you can retrieve your access token.<br><br>  ### How to retrieve an access token for a user #### Authorization grant type used is *authorization_code* ##### Step 1 Obtain an authorization code against your Jira Cloud instance :  `GET: https://{jira-cloud-instance-name}.atlassian.net/plugins/servlet/ac/io.tempo.jira/oauth-authorize/?client_id=$CLIENT_ID&redirect_uri=$REDIRECT_URI`  Where *$CLIENT_ID* and *$REDIRECT_URI* match the one you generated in **Tempo > Settings > OAuth 2.0 Applications**  You will be asked to *authorize* or *deny* access to your Tempo data. Granting access redirects you to the configured  *redirect URI* with a new query string parameter named *code* (this is the authorization code). Note that this authorization code  expires quickly.  ![MyApp Request Access](myapp-request-access.png \"MyApp Request Access\")  ##### Step 2 Obtain an access token from Tempo by providing the *authorization code* to:  `POST: https://api.tempo.io/oauth/token/`  sending the following parameters using the \"application/x-www-form-urlencoded\" format: ``` grant_type = \"authorization_code\" client_id = $CLIENT_ID client_secret = $CLIENT_SECRET redirect_uri = $REDIRECT_URI code = $CODE ```  The response includes the access token itself, related information, and a refresh token. ```JSON {   \"access_token\":\"$ACCESS_TOKEN\",   \"expires_in\":5184000,   \"token_type\":\"Bearer\",   \"scope\":\"read write\",   \"refresh_token\":\"$REFRESH_TOKEN\" } ```  ##### Step 3 Provide this *access token* to any API requests using the *Authorization header* :  `curl -H \"Authorization: Bearer $ACCESS_TOKEN\" \"https://api.tempo.io/4/worklogs?from=2022-01-28&to=2022-02-03\"`  The access token will expire after the number of seconds specified in the **expires_in** field and will  no longer be usable.  ### How to retrieve a new access token from the refresh token The *access token* will eventually expire. You need to renew it using the previously received *refresh token*:  `POST: https://api.tempo.io/oauth/token/`  sending the following parameters using the \"application/x-www-form-urlencoded\" format: ``` grant_type = \"refresh_token\" client_id = $CLIENT_ID client_secret = $CLIENT_SECRET redirect_uri = $REDIRECT_URI refresh_token = $REFRESH_TOKEN ```  The response will contain a new *access token* and a new *refresh token*. You'll need to utilize these  new tokens for future calls, as the previous ones will no longer be valid.  ### How to revoke a token You can revoke an existing *access token* at any time:  `POST: https://api.tempo.io/oauth/revoke_token/`  sending the following parameters using the \"application/x-www-form-urlencoded\" format: ``` token_type_hint = \"access_token\" client_id = $CLIENT_ID client_secret = $CLIENT_SECRET token = $ACCESS_TOKEN ```  You can also revoke an existing *refresh token*:  `POST: https://api.tempo.io/oauth/revoke_token/`  sending the following parameters using the \"application/x-www-form-urlencoded\" format: ``` {   token_type_hint = \"refresh_token\"   client_id = $CLIENT_ID   client_secret = $CLIENT_SECRET   token = $REFRESH_TOKEN } ```  ## API conventions ### Identifying users The Tempo REST API uses the Atlassian accountId to identify users. The accountId is an opaque identifier that  uniquely identifies the user.  The accountId of the current user can found using the [Jira Myself API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-group-Myself).  Information about a user, given the accountId, can be retrieved using the [Jira User API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-group-User).  ### Dates The API uses strings to represent dates. Dates are formatted as [ISO 8601 calendar dates](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates) (YYYY-MM-DD).  For example, March 29th, 2019 is formatted as 2019-03-29.  ### Delete requests On success, delete requests return a response with status code [204 (No content)](https://httpstatuses.com/204).  No payload body is included in the response.  ### Arrays A few endpoints accept query parameters of type array. That is achieved by repeating the parameter multiple  times, e.g. to get worklogs from three projects:  `.../worklogs?from=2020-01-01&to=2020-12-31&project=10100&project=10200&project=10300`  ## Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call.  Here are a list of different types of error responses  Status code  | Description | Content type ----------------|-------------|--------- 400 | Bad Request | application/json 401 | Unauthorized | text/html 403 | Forbidden | text/html 404 | Not Found | application/json  <br>  The body of the JSON response will be in the following format:  ``` {   \"errors\": {     \"message\": \"Error details\"   } } ```  An example of 400 error ```   {     \"errors\": {       \"message\": \"'date' must be valid on the format: 'yyyy-MM-dd'\"     }   } ```  An example of 404 error ```   {     \"errors\": {       \"message\": \"Account 'xyz' not found\"     }   } ``` 

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account'
require 'openapi_client/models/account_input'
require 'openapi_client/models/account_link'
require 'openapi_client/models/account_link_input'
require 'openapi_client/models/account_link_results'
require 'openapi_client/models/account_link_scope'
require 'openapi_client/models/account_search_input'
require 'openapi_client/models/account_user'
require 'openapi_client/models/category'
require 'openapi_client/models/category_input'
require 'openapi_client/models/category_results'
require 'openapi_client/models/category_type'
require 'openapi_client/models/category_type_results'
require 'openapi_client/models/create_work_attribute_input'
require 'openapi_client/models/customer'
require 'openapi_client/models/customer_input'
require 'openapi_client/models/day_schedule'
require 'openapi_client/models/day_schedule_results'
require 'openapi_client/models/entity'
require 'openapi_client/models/generic_resource'
require 'openapi_client/models/generic_resource_input'
require 'openapi_client/models/generic_resource_reference'
require 'openapi_client/models/generic_resource_search_input'
require 'openapi_client/models/generic_resource_team_member'
require 'openapi_client/models/generic_resource_team_member_input'
require 'openapi_client/models/generic_resource_team_members'
require 'openapi_client/models/global_configuration'
require 'openapi_client/models/holiday'
require 'openapi_client/models/holiday_input'
require 'openapi_client/models/holiday_results'
require 'openapi_client/models/holiday_scheme'
require 'openapi_client/models/holiday_scheme_input_bean'
require 'openapi_client/models/holiday_scheme_members_input'
require 'openapi_client/models/holiday_scheme_results'
require 'openapi_client/models/issue'
require 'openapi_client/models/membership_input'
require 'openapi_client/models/model_self'
require 'openapi_client/models/pageable'
require 'openapi_client/models/pageable_account'
require 'openapi_client/models/pageable_account_link'
require 'openapi_client/models/pageable_customer'
require 'openapi_client/models/pageable_generic_resource_without_self_link'
require 'openapi_client/models/pageable_metadata'
require 'openapi_client/models/pageable_permission_role'
require 'openapi_client/models/pageable_plan_without_self_link'
require 'openapi_client/models/pageable_skill'
require 'openapi_client/models/pageable_team'
require 'openapi_client/models/pageable_team_link'
require 'openapi_client/models/pageable_tempo_to_jira_worklog_id'
require 'openapi_client/models/pageable_user'
require 'openapi_client/models/pageable_without_self_link'
require 'openapi_client/models/pageable_work_attribute'
require 'openapi_client/models/pageable_workload_scheme'
require 'openapi_client/models/pageable_worklog'
require 'openapi_client/models/permission'
require 'openapi_client/models/permission_role'
require 'openapi_client/models/permission_role_input'
require 'openapi_client/models/plan'
require 'openapi_client/models/plan_approval'
require 'openapi_client/models/plan_approval_input'
require 'openapi_client/models/plan_assignee'
require 'openapi_client/models/plan_day'
require 'openapi_client/models/plan_input'
require 'openapi_client/models/plan_item'
require 'openapi_client/models/plan_metadata'
require 'openapi_client/models/plan_period'
require 'openapi_client/models/plan_results'
require 'openapi_client/models/plan_search_input'
require 'openapi_client/models/planned_time'
require 'openapi_client/models/planned_time_values_plan_day'
require 'openapi_client/models/planned_time_values_plan_period'
require 'openapi_client/models/program'
require 'openapi_client/models/program_input'
require 'openapi_client/models/program_reference'
require 'openapi_client/models/program_results'
require 'openapi_client/models/results_metadata'
require 'openapi_client/models/role'
require 'openapi_client/models/role_input'
require 'openapi_client/models/role_reference'
require 'openapi_client/models/role_results'
require 'openapi_client/models/self_api_bean'
require 'openapi_client/models/self_link'
require 'openapi_client/models/self_list_team_ref'
require 'openapi_client/models/self_list_work_attribute_value'
require 'openapi_client/models/self_member'
require 'openapi_client/models/skill'
require 'openapi_client/models/skill_input'
require 'openapi_client/models/skills_assignment_input'
require 'openapi_client/models/team'
require 'openapi_client/models/team_input'
require 'openapi_client/models/team_lead'
require 'openapi_client/models/team_link'
require 'openapi_client/models/team_link_input'
require 'openapi_client/models/team_link_results'
require 'openapi_client/models/team_link_scope'
require 'openapi_client/models/team_member'
require 'openapi_client/models/team_membership'
require 'openapi_client/models/team_membership_input'
require 'openapi_client/models/team_membership_results'
require 'openapi_client/models/team_ref'
require 'openapi_client/models/team_ref_results'
require 'openapi_client/models/team_reference'
require 'openapi_client/models/tempo_to_jira_worklog_id'
require 'openapi_client/models/tempo_worklog_id_list'
require 'openapi_client/models/timesheet_approval'
require 'openapi_client/models/timesheet_approval_actor'
require 'openapi_client/models/timesheet_approval_available_actions'
require 'openapi_client/models/timesheet_approval_input'
require 'openapi_client/models/timesheet_approval_period'
require 'openapi_client/models/timesheet_approval_periods_bean'
require 'openapi_client/models/timesheet_approval_results'
require 'openapi_client/models/timesheet_approval_reviewer'
require 'openapi_client/models/timesheet_approval_status'
require 'openapi_client/models/timesheet_approval_user'
require 'openapi_client/models/update_work_attribute_input'
require 'openapi_client/models/user'
require 'openapi_client/models/user_contact'
require 'openapi_client/models/user_ref_bean'
require 'openapi_client/models/user_results'
require 'openapi_client/models/work_attribute'
require 'openapi_client/models/work_attribute_value'
require 'openapi_client/models/work_attribute_value_input'
require 'openapi_client/models/work_attribute_value_results'
require 'openapi_client/models/work_attribute_values_input'
require 'openapi_client/models/workload_scheme'
require 'openapi_client/models/workload_scheme_day'
require 'openapi_client/models/workload_scheme_day_input'
require 'openapi_client/models/workload_scheme_input'
require 'openapi_client/models/workload_scheme_members_input'
require 'openapi_client/models/worklog'
require 'openapi_client/models/worklog_input'
require 'openapi_client/models/worklog_search_input'

# APIs
require 'openapi_client/api/account_categories_api'
require 'openapi_client/api/account_category_types_api'
require 'openapi_client/api/account_links_api'
require 'openapi_client/api/accounts_api'
require 'openapi_client/api/customers_api'
require 'openapi_client/api/generic_resource_team_members_api'
require 'openapi_client/api/generic_resources_api'
require 'openapi_client/api/global_configurations_api'
require 'openapi_client/api/holiday_schemes_api'
require 'openapi_client/api/periods_api'
require 'openapi_client/api/permission_roles_api'
require 'openapi_client/api/plans_api'
require 'openapi_client/api/program_api'
require 'openapi_client/api/roles_api'
require 'openapi_client/api/skill_assignments_api'
require 'openapi_client/api/skills_api'
require 'openapi_client/api/team_api'
require 'openapi_client/api/team_links_api'
require 'openapi_client/api/team_memberships_api'
require 'openapi_client/api/timesheet_approvals_api'
require 'openapi_client/api/user_schedule_api'
require 'openapi_client/api/work_attributes_api'
require 'openapi_client/api/workload_schemes_api'
require 'openapi_client/api/worklogs_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
